name: banking_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"
dependencies:
  cached_network_image: ^3.2.1
  carousel_slider: ^4.1.1
  cupertino_icons: ^1.0.2
  easy_localization: ^3.0.1
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.5.3+2
  flutter_spinkit: ^5.1.0
  flutter_svg: ^1.1.1+1
  fluttertoast: ^8.0.9
  http: ^0.13.5
  intl: ^0.17.0
  json_serializable: ^6.3.1
  lottie: ^1.4.2
  provider: ^6.0.3
  shared_preferences: ^2.0.15
  smooth_page_indicator: ^1.0.0+2
  sqflite: ^2.0.3+1

dev_dependencies:
  build_runner: ^2.2.0

  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/lottie/
    - assets/images/
    - assets/translations/
    - assets/svg/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Thin.ttf
          weight: 200
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins/Poppins-Black.ttf
          weight: 900
